[queues]
input_queue_name = "solana.sol.transfer"
output_queue_name = "result"

[rpc]
http_endpoint_url = "http://localhost:8899"
ws_endpoint_url = "http://localhost:8900"

[db]
payments_path = "/var/lib/tx-checker/db/solana/payments"
height_path = "/var/lib/tx-checker/db/solana/height"